'use strict';
console.log(`The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
`);

let _ = require('underscore');

let divisors = function(n) { // if this function is used, the answer is not computed
                             // within a reasonable amount of time.
    return _.range(1, n+1).filter( (x)=> n%x === 0);
};

let divisorsFast = function(n) {
    var upTo = Math.floor(Math.sqrt(n));
    var rv = [];
    _.range(1, upTo+1).reduce( function(prevValue, currEl) {
        if (n % currEl === 0) {
            prevValue.push(currEl);
            prevValue.push(n / currEl);
        }
        return prevValue;
    }, rv);
    return rv;
};



let triangular = function(n) {
    return _.range(1, n+1).reduce( (a,b)=>(a+b), 0);
};


const N = 500;
let rv = (function() {
    for (let i = 0; ; i++) {
        let ti = triangular(i);
        let divs = divisorsFast( ti );
        if (divs.length > N)
            return ti;
    }
    throw new Error('impossible');
})();

console.log(rv);
